{% set name = "aliyun-python-sdk-kms" %}
{% set version = "2.16.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d5bb165c07b6a972939753a128507393f48011792ee0ec4f59b6021eabd9752

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - aliyun-python-sdk-core >=2.11.5

test:
  requires:
    - python {{ python_min }}
  imports:
    - aliyunsdkkms

about:
  home: http://develop.aliyun.com/sdk/python
  license: Apache-2.0
  license_file: LICENSE
  summary: Aliyun Python SDK is the official software development kit.

  description: |
    Aliyun Python SDK is the official software development kit. It
    makes things easy to integrate your Python application, library,
    or script with Aliyun services.

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
